
package com.yue.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WbserviceImplService", targetNamespace = "http://ws.yue.com/", wsdlLocation = "http://192.168.11.198:8089/FrameworkStudy/Webservice?wsdl")
public class WbserviceImplService
    extends Service
{

    private final static URL WBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.yue.com/", "WbserviceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.11.198:8089/FrameworkStudy/Webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WbserviceImplService() {
        super(__getWsdlLocation(), WBSERVICEIMPLSERVICE_QNAME);
    }

    public WbserviceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WBSERVICEIMPLSERVICE_QNAME, features);
    }

    public WbserviceImplService(URL wsdlLocation) {
        super(wsdlLocation, WBSERVICEIMPLSERVICE_QNAME);
    }

    public WbserviceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WBSERVICEIMPLSERVICE_QNAME, features);
    }

    public WbserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WbserviceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WbserviceImpl
     */
    @WebEndpoint(name = "WbserviceImplPort")
    public WbserviceImpl getWbserviceImplPort() {
        return super.getPort(new QName("http://ws.yue.com/", "WbserviceImplPort"), WbserviceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WbserviceImpl
     */
    @WebEndpoint(name = "WbserviceImplPort")
    public WbserviceImpl getWbserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.yue.com/", "WbserviceImplPort"), WbserviceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
