
package com.yue.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WbserviceImpl", targetNamespace = "http://ws.yue.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WbserviceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tobytest", targetNamespace = "http://ws.yue.com/", className = "com.yue.ws.Tobytest")
    @ResponseWrapper(localName = "tobytestResponse", targetNamespace = "http://ws.yue.com/", className = "com.yue.ws.TobytestResponse")
    @Action(input = "http://ws.yue.com/WbserviceImpl/tobytestRequest", output = "http://ws.yue.com/WbserviceImpl/tobytestResponse")
    public String tobytest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
